---
title: "Assignment 05"
author: "Rodal Issema"
date: "2/10/2022"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 6
    self_contained: true
    number_sections: false
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse, magrittr, ISOcodes, HMDHFDplus, keyring, captioner)

figure_nums <- captioner(prefix = "Figure")

```

## R Markdown

```{r}
# HFD country codes
hfdcodes <- getHFDcountries() %>% tibble(ccode = .)

# ISO country codes
isocodes <- ISO_3166_1 %>% tibble() %>% select(ccode = Alpha_3, Name)

# join ISO codes with country names
hfdcodes %<>% 
  left_join(isocodes, by = "ccode") 

#Function download data
read_country <- function(CNTRY, item) {
  readHFDweb(
    CNTRY = CNTRY,
    item = item,
    username = key_list("human-mortality-database")$username,
    password = key_get(
      service = "human-mortality-database",
      username = key_list("human-mortality-database")$username
    )
  )
}

#Function to read items
read_countries_item <- function(countries, item){
    countries %>%
        map_dfr(function(ccode) {
            read_country(ccode, item) %>%
                mutate(ccode = ccode)
        }) %>%
        tibble() %>% 
        left_join(hfdcodes, by = "ccode")
}

# Countries of interest
CNTRIES <- hfdcodes %>% 
    filter(Name %in% c("Sweden", "Norway", "Finland")) %>% 
    pull(ccode)

```

## Live births

```{r}
totbirthsSWE_NOR_FIN <- read_countries_item(countries = CNTRIES, item = "totbirthsRR")

totbirthsSWE_NOR_FIN %>% 
    mutate(TotalM = Total / 1000000) %>% 
    ggplot( 
       mapping = aes(x = Year, y = TotalM)) +
    geom_line() +
    facet_wrap(~Name, ncol = 1, scales = "free_y") +
    ylab("Live Births") +
    xlab("Year")

```
\    
*`r figure_nums(name = "LiveBirths", caption = "Live births x 1 million: Sweden, Norway, and Finland (Y scale not standardized)")`*

## Mean Age at birth

```{r}
mabSWE_NOR_FIN <- read_countries_item(countries = CNTRIES, item = "mabRR")

mabSWE_NOR_FIN %>% 
    # mutate(TotalM = Total / 1000000) %>% 
    ggplot( 
       mapping = aes(x = Year, y = MAB)) +
    geom_line() +
    facet_wrap(~Name, ncol = 1, scales = "free_y") +
    ylab("Mean age at birth") +
    xlab("year")
```

\    
*`r figure_nums(name = "MeanAgeBirths", caption = "Mean age at birth: Sweden, Norway, and Finland (Y scale not standardized)")`*